# Generated by Django 5.2.6 on 2025-12-02 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_empresa_empresarole_userempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('nome_razao_social', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('qualificacao', models.CharField(blank=True, help_text='Varejo, Qualificado, Profissional', max_length=50)),
                ('perfil_investidor', models.CharField(blank=True, max_length=50)),
                ('data_suitability', models.DateField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=3)),
                ('agencia', models.CharField(blank=True, max_length=10)),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('dados_adicionais', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cotista',
                'verbose_name_plural': 'Cotistas',
                'db_table': 'cotistas',
                'ordering': ['nome_razao_social'],
                'indexes': [models.Index(fields=['cpf_cnpj'], name='cotistas_cpf_cnp_60ceda_idx'), models.Index(fields=['tipo_pessoa'], name='cotistas_tipo_pe_ffc13e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('codigo_anbima', models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True)),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_comercial', models.CharField(blank=True, max_length=200)),
                ('tipo_fundo', models.CharField(choices=[('FII', 'Fundo de Investimento Imobiliário'), ('FIDC', 'Fundo de Investimento em Direitos Creditórios'), ('FIP', 'Fundo de Investimento em Participações')], max_length=10)),
                ('data_constituicao', models.DateField()),
                ('tipo_cotizacao', models.CharField(default='D+0', help_text='D+0 ou D+1', max_length=10)),
                ('prazo_liquidacao', models.IntegerField(default=0, help_text='Dias úteis')),
                ('horario_corte', models.TimeField(default='14:00')),
                ('taxa_administracao', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('taxa_gestao', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('politica_investimento', models.JSONField(blank=True, null=True)),
                ('dados_adicionais', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundos', to='usuarios.empresa')),
            ],
            options={
                'verbose_name': 'Fundo',
                'verbose_name_plural': 'Fundos',
                'db_table': 'fundos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='CotaHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_referencia', models.DateField(db_index=True)),
                ('valor_cota', models.DecimalField(decimal_places=6, max_digits=16)),
                ('patrimonio_liquido', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantidade_cotas', models.DecimalField(decimal_places=6, max_digits=18)),
                ('quantidade_cotistas', models.IntegerField(default=0)),
                ('captacao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('resgate_dia', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('rentabilidade_dia', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rentabilidade_mes', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rentabilidade_ano', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('enviado_anbima', models.BooleanField(default=False)),
                ('data_envio_anbima', models.DateTimeField(blank=True, null=True)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotas_historico', to='fundos.fundo')),
            ],
            options={
                'verbose_name': 'Histórico de Cota',
                'verbose_name_plural': 'Histórico de Cotas',
                'db_table': 'cotas_historico',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_ativo', models.CharField(max_length=50)),
                ('codigo_isin', models.CharField(blank=True, max_length=12)),
                ('codigo_negociacao', models.CharField(blank=True, max_length=20)),
                ('emissor_cnpj', models.CharField(blank=True, max_length=14)),
                ('emissor_nome', models.CharField(blank=True, max_length=200)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('preco_aquisicao', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('preco_mercado', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('valor_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('taxa_cupom', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('indexador', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('dados_adicionais', models.JSONField(blank=True, null=True)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='fundos.fundo')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'db_table': 'ativos',
                'ordering': ['-data_aquisicao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_movimentacao', models.CharField(choices=[('APLICACAO', 'Aplicação'), ('RESGATE', 'Resgate'), ('COME_COTAS', 'Come-Cotas')], max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_cotizacao', models.DateField()),
                ('data_liquidacao', models.DateField()),
                ('valor_financeiro', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('valor_cota', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('quantidade_cotas', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ir_retido', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('iof_retido', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=25)),
                ('dados_adicionais', models.JSONField(blank=True, null=True)),
                ('cotista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='fundos.cotista')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='fundos.fundo')),
            ],
            options={
                'verbose_name': 'Movimentação de Cota',
                'verbose_name_plural': 'Movimentações de Cotas',
                'db_table': 'movimentacoes_cotas',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Recebiveis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedente_cnpj', models.CharField(db_index=True, max_length=14)),
                ('cedente_nome', models.CharField(max_length=200)),
                ('sacado_cpf_cnpj', models.CharField(db_index=True, max_length=14)),
                ('sacado_nome', models.CharField(max_length=200)),
                ('tipo_credito', models.CharField(max_length=50)),
                ('numero_titulo', models.CharField(max_length=50)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valor_cessao', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('A_ENVIAR', 'A Enviar'), ('EM_COBRANCA', 'Em Cobrança'), ('A_VENCER', 'A Vencer'), ('VENCIDO', 'Vencido'), ('PAGO', 'Pago'), ('BAIXADO', 'Baixado'), ('REJEITADO', 'Rejeitado')], default='A_VENCER', max_length=30)),
                ('dias_atraso', models.IntegerField(default=0)),
                ('pdd_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pdd_valor', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('dados_adicionais', models.JSONField(blank=True, null=True)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebiveis', to='fundos.fundo')),
            ],
            options={
                'verbose_name': 'Recebível',
                'verbose_name_plural': 'Recebíveis',
                'db_table': 'recebiveis',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.AddIndex(
            model_name='fundo',
            index=models.Index(fields=['cnpj'], name='fundos_cnpj_d30dda_idx'),
        ),
        migrations.AddIndex(
            model_name='fundo',
            index=models.Index(fields=['codigo_anbima'], name='fundos_codigo__d68f69_idx'),
        ),
        migrations.AddIndex(
            model_name='fundo',
            index=models.Index(fields=['empresa', 'ativo'], name='fundos_empresa_131f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='cotahistorico',
            index=models.Index(fields=['fundo', '-data_referencia'], name='cotas_histo_fundo_i_75f356_idx'),
        ),
        migrations.AddIndex(
            model_name='cotahistorico',
            index=models.Index(fields=['data_referencia'], name='cotas_histo_data_re_660f38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotahistorico',
            unique_together={('fundo', 'data_referencia')},
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['fundo', 'ativo'], name='ativos_fundo_i_7bcbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['tipo_ativo'], name='ativos_tipo_at_4c5bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocota',
            index=models.Index(fields=['fundo', 'data_cotizacao'], name='movimentaco_fundo_i_0b7994_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocota',
            index=models.Index(fields=['cotista', 'status'], name='movimentaco_cotista_d55726_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocota',
            index=models.Index(fields=['status'], name='movimentaco_status_493afa_idx'),
        ),
        migrations.AddIndex(
            model_name='recebiveis',
            index=models.Index(fields=['fundo', 'status'], name='recebiveis_fundo_i_6b4823_idx'),
        ),
        migrations.AddIndex(
            model_name='recebiveis',
            index=models.Index(fields=['cedente_cnpj'], name='recebiveis_cedente_6b0f54_idx'),
        ),
        migrations.AddIndex(
            model_name='recebiveis',
            index=models.Index(fields=['sacado_cpf_cnpj'], name='recebiveis_sacado__c71e77_idx'),
        ),
        migrations.AddIndex(
            model_name='recebiveis',
            index=models.Index(fields=['data_vencimento'], name='recebiveis_data_ve_77ffcf_idx'),
        ),
    ]
