# Generated by Django 5.2.6 on 2026-04-09 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeMensal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.DateField(db_index=True, help_text='Primeiro dia do mês de competência. Ex: 2026-02-01 para 02/2026.')),
                ('versao_xml', models.CharField(blank=True, max_length=10)),
                ('cnpj_administrador', models.CharField(blank=True, max_length=14)),
                ('arquivo_xml_nome', models.CharField(blank=True, max_length=255)),
                ('vl_disponib', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_carteira', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_total_ativos', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_dicred', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_dicred_cedent', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_dicred_inad', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_dicred_venc_inad', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_total_passivo', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_pgto_curprz', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_pgto_lprazo', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_patrimonio_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_patrimonio_liquido_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('qt_cotas_subord', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('vl_cota_subord', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('qt_cotas_senior', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('vl_cota_senior', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('qt_total_cotistas', models.IntegerField(blank=True, null=True)),
                ('qt_cotistas_senior', models.IntegerField(blank=True, null=True)),
                ('qt_cotistas_subord', models.IntegerField(blank=True, null=True)),
                ('rentabilidade_senior', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rentabilidade_subord', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('desemp_esp_senior', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('desemp_real_senior', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('desemp_esp_subord', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('desemp_real_subord', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('vl_liqdez_30', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_liqdez_60', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_liqdez_90', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_liqdez_180', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_liqdez_360', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_liqdez_mais_360', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_venc_30', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_venc_31_60', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_venc_61_90', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_venc_91_120', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_venc_121_180', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_venc_181_360', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_venc_361_720', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_venc_mais_720', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_capt_senior', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_capt_subord', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_resg_senior', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_resg_subord', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_rating_aa', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_rating_a', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_rating_b', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_rating_c', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('vl_rating_d_h', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('dados_brutos', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_importados', to=settings.AUTH_USER_MODEL)),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_mensais', to='fundos.fundo')),
            ],
            options={
                'verbose_name': 'Informe Mensal',
                'verbose_name_plural': 'Informes Mensais',
                'db_table': 'fundos_informe_mensal',
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='InformeMensalCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(choices=[('SETOR_PUBLICO', 'Setor Público'), ('INDUSTRIAL', 'Industrial'), ('COMERCIAL', 'Comercial'), ('SERVICOS', 'Serviços'), ('AGRONEG', 'Agronegócio'), ('FINANCEIRO', 'Financeiro'), ('FACTORING', 'Factoring'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('VALORES_MOBILIARIOS', 'Valores Mobiliários'), ('ACAO_JUDIC', 'Ação Judicial'), ('OUTROS', 'Outros')], max_length=50)),
                ('subsegmento', models.CharField(blank=True, max_length=80, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('percentual_carteira', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteira', to='fundos.informemensal')),
            ],
            options={
                'verbose_name': 'Segmento de Carteira',
                'verbose_name_plural': 'Segmentos de Carteira',
                'db_table': 'fundos_informe_mensal_carteira',
                'ordering': ['-valor'],
            },
        ),
        migrations.CreateModel(
            name='InformeMensalCedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_pf_pj_cedent', models.CharField(max_length=14)),
                ('pr_cedent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedentes', to='fundos.informemensal')),
            ],
            options={
                'verbose_name': 'Cedente do Informe',
                'verbose_name_plural': 'Cedentes do Informe',
                'db_table': 'fundos_informe_mensal_cedente',
                'ordering': ['-pr_cedent'],
            },
        ),
        migrations.AddIndex(
            model_name='informemensal',
            index=models.Index(fields=['fundo', '-competencia'], name='fundos_info_fundo_i_a25c3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='informemensal',
            unique_together={('fundo', 'competencia')},
        ),
        migrations.AlterUniqueTogether(
            name='informemensalcarteira',
            unique_together={('informe', 'segmento', 'subsegmento')},
        ),
    ]
