# Generated by Django 5.2.6 on 2025-11-13 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('pode_gerenciar_usuarios', models.BooleanField(default=False)),
                ('pode_ver_fundos', models.BooleanField(default=True)),
                ('pode_ver_lastro', models.BooleanField(default=False)),
                ('pode_ver_risco', models.BooleanField(default=False)),
                ('pode_ver_conformidade', models.BooleanField(default=False)),
                ('pode_ver_relatorios', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='usuarios.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='UserEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.empresarole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
