# Generated by Django 5.2.6 on 2026-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_empresarole_userempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresarole',
            name='pode_importar_informes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresarole',
            name='pode_ver_informes',
            field=models.BooleanField(default=True),
        ),
    ]
